#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# 04-gen-warpdrive-config.sh
# Generates the WarpDrive YAML config for the two Azure Blob
# backends and writes it to /etc/warpdrive/config.yaml.
#
# Run ON the VM after 03-vm-setup.sh.
# Requires STORAGE_ACCOUNT_A and STORAGE_ACCOUNT_B to be set
# (either via env or infra/.env.generated).
# ──────────────────────────────────────────────────────────────
set -euo pipefail

STORAGE_ACCOUNT_A="${STORAGE_ACCOUNT_A:?Set STORAGE_ACCOUNT_A (the canadacentral storage account name)}"
STORAGE_ACCOUNT_B="${STORAGE_ACCOUNT_B:?Set STORAGE_ACCOUNT_B (the westus3 storage account name)}"
CONTAINER_NAME="${CONTAINER_NAME:-coco2017-wds}"
WD_MOUNT_POINT="${WD_MOUNT_POINT:-/wd}"
WD_CACHE_DIR="${WD_CACHE_DIR:-/mnt/nvme/warpdrive-cache}"
WD_CACHE_SIZE="${WD_CACHE_SIZE:-50GB}"
CONFIG_PATH="${CONFIG_PATH:-/etc/warpdrive/config.yaml}"

sudo mkdir -p "$(dirname "$CONFIG_PATH")"

echo "==> Writing WarpDrive config to $CONFIG_PATH"

sudo tee "$CONFIG_PATH" > /dev/null <<EOF
# WarpDrive config for warpdrive-forge
# Generated by infra/04-gen-warpdrive-config.sh
mount_point: ${WD_MOUNT_POINT}
allow_other: true

cache:
  path: ${WD_CACHE_DIR}
  max_size: ${WD_CACHE_SIZE}
  block_size: 4MB
  readahead_blocks: 8
  max_parallel_fetch: 32
  evict_high_water: 0.90
  evict_low_water: 0.80

backends:
  # Canada Central — even-numbered shards
  - name: datasets-cac
    type: azureblob
    mount_path: /datasets-cac
    config:
      account: ${STORAGE_ACCOUNT_A}
      root: ${CONTAINER_NAME}
      chunk_size: "4194304"
      list_chunk: "5000"
      env_auth: "true"
      use_msi: "true"
    auth:
      method: managed_identity

  # West US 3 — odd-numbered shards
  - name: datasets-wus3
    type: azureblob
    mount_path: /datasets-wus3
    config:
      account: ${STORAGE_ACCOUNT_B}
      root: ${CONTAINER_NAME}
      chunk_size: "4194304"
      list_chunk: "5000"
      env_auth: "true"
      use_msi: "true"
    auth:
      method: managed_identity

metrics:
  enabled: true
  addr: ":9090"

telemetry:
  enabled: false
  sink: nop
EOF

echo "    Mount point : $WD_MOUNT_POINT"
echo "    Cache       : $WD_CACHE_DIR ($WD_CACHE_SIZE)"
echo ""
echo "    Backend datasets-cac  → azureblob://$STORAGE_ACCOUNT_A/$CONTAINER_NAME"
echo "    Backend datasets-wus3 → azureblob://$STORAGE_ACCOUNT_B/$CONTAINER_NAME"
echo ""
echo "    Config keys (rclone-compatible):"
echo "      root       = $CONTAINER_NAME   (container name mapped to rclone root)"
echo "      chunk_size = 4194304           (required for azureblob)"
echo "      list_chunk = 5000              (required for azureblob)"
echo "      env_auth   = true              (let rclone handle MSI auth)"
echo "      use_msi    = true              (enable managed identity)"
echo ""
echo "    Paths visible after mount:"
echo "      ${WD_MOUNT_POINT}/datasets-cac/train/shard-000000.tar  (even shards)"
echo "      ${WD_MOUNT_POINT}/datasets-wus3/train/shard-000001.tar (odd  shards)"
echo ""
echo "Config written. Next: ./infra/05-run.sh"
